### ISSUE TITLE
Request for the pretrained checkpoint

### ISSUE THREAD

**Issue by mZhenz** [CVMI-Lab/KDEP#3]
Hi, could you offer some pretrained checkpoint, such as the resnet18 of KDEP_MS-R50_R18?

**Comment by RuiFeiHe** [comment]
Thanks for your advice, we will release some distilled ckpt soon~

**Comment by RuiFeiHe** [comment]
Hi, we've added some pretrained checkpoints, please check the updated README file.

**Comment by mZhenz** [comment]
Thanks a lot. It would be helpful.
